dist: xenial
language: 
   - cpp
os: linux
addons:
  apt:
    packages:
      - libqt4-dev
      - qt5-default
     
addons:
  sonarcloud:
    organization: "lusecnkodan-github"
    token:
      secure: $SONAR_TOKEN
      
before_install:
- pip install --user cpp-coveralls

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner

script:
- export QT_QPA_PLATFORM=offscreen
- qmake
- make
- "./tests/tests"
